**Task 1.1**


In [1]:
def main():
    # Nhập n
    n = int(input("Nhập số nguyên n: "))

    # Nhập n số nguyên x1, x2,..., xn rồi thêm chúng vào danh sách L.
    L = []
    for i in range(n):
        num = int(input(f"Nhập số nguyên thứ {i+1}: "))
        L.append(num)

    # Tìm phần tử max/min trong L.
    max_num = max(L)
    min_num = min(L)

    # Tính tổng các phần tử trong L.
    sum_nums = sum(L)

    # Sắp xếp danh sách L theo thứ tự tăng dần.
    sorted_L = sorted(L)

    # Cho biết có bao nhiêu số dương và số âm trong danh sách L.
    positive_count = sum(1 for num in L if num > 0)
    negative_count = sum(1 for num in L if num < 0)

    # Hiển thị kết quả
    print("Danh sách L:", L)
    print("Phần tử lớn nhất trong L:", max_num)
    print("Phần tử nhỏ nhất trong L:", min_num)
    print("Tổng các phần tử trong L:", sum_nums)
    print("Danh sách L sau khi sắp xếp:", sorted_L)
    print("Số lượng số dương trong L:", positive_count)
    print("Số lượng số âm trong L:", negative_count)

if __name__ == "__main__":
    main()

Nhập số nguyên n: 2
Nhập số nguyên thứ 1: 1
Nhập số nguyên thứ 2: 5
Danh sách L: [1, 5]
Phần tử lớn nhất trong L: 5
Phần tử nhỏ nhất trong L: 1
Tổng các phần tử trong L: 6
Danh sách L sau khi sắp xếp: [1, 5]
Số lượng số dương trong L: 2
Số lượng số âm trong L: 0


**Task 1.2**


In [ ]:
def calculate_S(n):
    if n <= 0:
        return "n phải lớn hơn 0"

    result = 0
    product = 1

    for i in range(1, n + 1):
        product *= i
        result += product

    return result

# Test the function
n = int(input("Nhập giá trị n: "))
print("Giá trị của S(n) là:", calculate_S(n))

Nhập giá trị n: 5
Giá trị của S(n) là: 153


**Task 1.3**

**Task 2.1**

In [ ]:
import numpy as np

# Tạo mảng từ 10 đến 25
arr = np.arange(10, 26)

# Đảo ngược mảng
reversed_arr = np.flip(arr)

print("Mảng gốc:", arr)
print("Mảng sau khi đảo ngược:", reversed_arr)

Mảng gốc: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
Mảng sau khi đảo ngược: [25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


**Task 2.2**

In [6]:
import numpy as np

# Mảng ban đầu
original_array = np.array([1, 2, 3, 4])

# Lặp lại mảng 2 lần
repeated_2_times = np.tile(original_array, 2)

# Lặp lại mảng 3 lần
repeated_3_times = np.tile(original_array, 3)

print("Mảng ban đầu:", original_array)
print("Lặp lại mảng 2 lần:", repeated_2_times)
print("Lặp lại mảng 3 lần:", repeated_3_times)

Mảng ban đầu: [1 2 3 4]
Lặp lại mảng 2 lần: [1 2 3 4 1 2 3 4]
Lặp lại mảng 3 lần: [1 2 3 4 1 2 3 4 1 2 3 4]


**Task 2.3**

In [7]:
import numpy as np

def replace_less_than(arr, value):
    # Tạo một bản sao của mảng để tránh thay đổi mảng gốc
    replaced_array = np.copy(arr)

    # Thay thế các phần tử nhỏ hơn giá trị đã chỉ định
    replaced_array[replaced_array < value] = value

    return replaced_array

# Mảng ban đầu
original_array = np.array([[0.42, 0.48, 0.32],
                           [0.74, 0.58, 0.38],
                           [0.51, 0.34, 0.15]])

# Giá trị để thay thế
specified_value = 0.5

# Hiển thị mảng ban đầu
print("Mảng ban đầu:")
print(original_array)

# Thay thế các phần tử của mảng ban đầu bằng giá trị chỉ định
result_array = replace_less_than(original_array, specified_value)

# Hiển thị kết quả
print("Thay thế tất cả các phần tử của mảng ban đầu bằng", specified_value, "đối với các giá trị lớn hơn", specified_value)
print(result_array)

Mảng ban đầu:
[[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.51 0.34 0.15]]
Thay thế tất cả các phần tử của mảng ban đầu bằng 0.5 đối với các giá trị lớn hơn 0.5
[[0.5  0.5  0.5 ]
 [0.74 0.58 0.5 ]
 [0.51 0.5  0.5 ]]
